### ISSUE TITLE
Provide explanation why to use these components over the Polymer ones

### ISSUE THREAD

**Issue by stevenroose** [dart-lang/angular2_components#38]
The Polymer project implements a whole range of Material components. These are supposed to be usable from any framework and there is even a PolymerDart implementation of (most of?) them.

It is not clear to the user (incl. me) what the added value is of using these components over the ones of the Polymer project.
I think it would be helpful to have a small explanatory section on this in the README.

**Comment by supermuka** [comment]
Great point! It is not never clear to me too. I think that a rich explanation about differences and goals each other will help all developers.

**Comment by zoechi** [comment]
I guess that should start with the differences between Polymer and Angular2
Angular2 has a strong focus on largish applications with a mandatory (at least for Dart) build step that allows (and requires) to do a lot of optimizations and allows more powerful features in the framework (for example where efficient code is generated for instead of using reflection which causes code bloat issues)

Polymer components are runtime only. There is no build step that can optimize for short load and fast initialization time or can generate code that is more efficient than reflective access.
This might change a bit with Polymer 2.0 with support for TypeScript which also requires a build step but they still need to support JS.

So, there are different sets of components to be able to gain the benefit of the respective platform.
- Polymer components - lightweight and reusable everywhere
- Angular2 components - optimized to work well with Angular2 change detection and code generation

**Comment by nshahan** [comment]
Thanks, I will add some text to the README.

The AngularDart components were designed to provide developers a standard set of material widgets for AngularDart applications. The feature set and performance is similar to the Polymer components but being able to debug your apps across all layers in Dart, supporting tree shaking for minimal code size and strict latency policies make it an excellent fit for AngularDart projects.

Polymer has a great set components and we are excited about the future of web components. As these standards get widely adopted across all browsers without polyfills we will certainly reconsider our recommendation and revisit internals of AngularDart itself. 

For the foreseeable future we believe AngularDart components are a productive and stable set of widgets, contributed to by hundreds of Googlers. They have proven successful in our projects and we think you will love using these in yours.

**Comment by nshahan** [comment]
Added a simple explanation text to the README in #48.
